name: "tf-manage project"
description: "Deploy a Terraform project using tf-manage"
inputs:
  token:
    description: "Explicitely provide secrets.GITHUB_TOKEN here"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout PR
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        echo "I am here"
