name: Dispatch

run-name: "@${{ github.actor }} triggered a plan for ${{ github.event_name }} ${{ github.ref }}"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'deploy/**'

permissions:
  pull-requests: write

jobs:
  discover:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - uses: sorinlg-beta/promotion-actions/checkout-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        uses: hmarr/debug-action@v3

      - name: Test
        run: |
          test='${{ github.event.pull_request.head.ref }}'
          echo "test: ${test}"

      - id: get_promotion_settings
        name: Discover promotion settings
        shell: bash
        run: ./scripts/detect_environments.sh
        env:
          # GITHUB_REF: ${{ env.GITHUB_REF }} # push event
          GITHUB_REF: ${{ github.event.pull_request.head.ref }} # pr sync event

    outputs:
      target_executions: ${{ toJson(steps.get_promotion_settings.outputs.target_executions) }}
      target_envs: ${{ toJson(steps.get_promotion_settings.outputs.target_envs) }}
      tfmEnvironment: ${{ steps.get_promotion_settings.outputs.target_envs }}

  meta:
    needs: discover
    uses: ./.github/workflows/meta.yaml
    strategy:
      matrix:
        tfmEnvironment: ${{ fromJson(needs.discover.outputs.tfmEnvironment) }}
    with:
      tfmEnvironment: ${{ matrix.tfmEnvironment }}
    # secrets:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   JENKINS_ROLE_ARN: ${{ secrets.JENKINS_ROLE_ARN }}
    #   NETWORKING_ACCOUNT_ROLE_ARN: ${{ secrets.NETWORKING_ACCOUNT_ROLE_ARN }}
