name: Plan

run-name: "@${{ github.actor }} triggered a plan for ${{ github.event_name }} ${{ github.ref }}"

on:
  push:
    branches:
      - deploy/**

jobs:
  discover:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - uses: sorinlg-beta/promotion-actions/checkout-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: get_promotion_settings
        name: Discover promotion settings
        shell: bash
        run: ./scripts/detect_environments.sh
        env:
          GITHUB_REF: ${{ env.GITHUB_REF }}

    outputs:
      target_executions: ${{ toJson(steps.get_promotion_settings.outputs.target_executions) }}
      target_envs: ${{ toJson(steps.get_promotion_settings.outputs.target_envs) }}
      tfmEnvironment: ${{ steps.get_promotion_settings.outputs.target_envs }}

  test:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tfmEnvironment: ${{ fromJson(needs.discover.outputs.tfmEnvironment) }}
    steps:
      - run: |
          current_env="${{ matrix.tfmEnvironment }}"
          echo "Current environment: ${current_env}"

  plan:
    needs: discover
    uses: ./.github/workflows/reusable-tfm.yaml
    strategy:
      matrix:
        tfmEnvironment: ${{ fromJson(needs.discover.outputs.tfmEnvironment) }}
    with:
      tfmProject: project1
      tfmEnvironment: ${{ matrix.tfmEnvironment }}
      tfmModule: sample_module
      tfmModuleInstance: instance_foo
      target_executions: ${{ needs.discover.outputs.target_executions }}
      target_envs: ${{ needs.discover.outputs.target_envs }}
    # secrets:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   JENKINS_ROLE_ARN: ${{ secrets.JENKINS_ROLE_ARN }}
    #   NETWORKING_ACCOUNT_ROLE_ARN: ${{ secrets.NETWORKING_ACCOUNT_ROLE_ARN }}
