# name: promotion-init

# on:
#   push:
#     branches:
#       - develop
#   pull_request_review:
#     types: [submitted]
#   check_run:
#     types: [completed]
#   check_suite:
#     types: [completed]
#   deployment_status: ~
#   status: ~

# permissions:
#   contents: write
#   pull-requests: write
#   statuses: write

# jobs:
#   initiate:
#     name: Initiate
#     if: ${{ github.event_name == 'push' }}
#     runs-on: ubuntu-latest
#     timeout-minutes: 5
#     steps:
#       - uses: actions/checkout@v4
#       - name: Request Promotion
#         uses: sorinlg-beta/promotion-actions/open-promotion-request@main
#         with:
#           stages: |
#             ["develop", "main", "staging:auto", "canary", "production"]
#           source: "${{ github.ref }}"

#   progress:
#     name: Progress
#     if: ${{ github.event_name != 'push' }}
#     runs-on: ubuntu-latest
#     timeout-minutes: 5
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           ref: ${{ github.ref }}
#           fetch-depth: 0
#       - name: Find Promotion Request
#         id: find
#         uses: sorinlg-beta/promotion-actions/find-promotion-request@main
#         with:
#           targetRefs: '["main", "staging", "canary", "production"]'
#       - name: Fast-Forward Merge
#         id: merge
#         if: ${{ steps.find.outputs.promoteable == 'true' }}
#         uses: sorinlg-beta/promotion-actions/fast-forward-merge@main
#         with:
#           baseRef: ${{ steps.find.outputs.baseRef }}
#           headRef: ${{ steps.find.outputs.headRef }}
#       - name: Request Promotion
#         id: promote
#         if: ${{ steps.find.outputs.promoteable == 'true' }}
#         uses: sorinlg-beta/promotion-actions/open-promotion-request@main
#         with:
#           stages: '["develop", "main", "staging:auto", "canary", "production"]'
#           source: ${{ steps.find.outputs.baseRef }}


name: promotion-init

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write
  statuses: write

env:
  STAGES: |
    ["develop", "main", "staging:auto", "canary", "production"]

jobs:
  initiate:
    name: Initiate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Request Promotion
        uses: sorinlg-beta/promotion-actions/open-promotion-request@main
        with:
          stages: ${{ env.STAGES }}
          source: "${{ github.ref }}"
