name: promotion-progress

run-name: "@${{ github.actor }}'s PR triggered a promotion analysis"

on:
  pull_request_review:
    types: [submitted]
  check_run:
    types: [completed]
  check_suite:
    types: [completed]
  deployment_status: ~
  status: ~

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  discover:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - uses: sorinlg-beta/promotion-actions/checkout-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: get_promotion_settings
        name: Discover promotion settings
        shell: bash
        run: |
          source .tfm.conf
          echo "Config path: ${__tfm_env_rel_path}"
          projects=`ls -A ${__tfm_env_rel_path}`

          echo "Found projects:"
          for project in ${projects}; do
            echo "  - ${project}"
          done

          echo "The discovered promotion settings:"
          ls -la promotion_settings.yaml
          rules=`cat promotion_settings.yaml | yq -o json | jq -c '.'`

          echo
          echo "Found rules:"
          echo "${rules}" | yq -p json

          # store output
          echo "rules=${rules}" >> $GITHUB_OUTPUT
    outputs:
      map: ${{ toJson(steps.get_promotion_settings.outputs.rules) }}

  progress:
    name: Progress
    needs: discover
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Get promotion settings
        id: get_promotion_settings
        run: |
          settings="${{ needs.discover.outputs.map }}"
          echo "Found settings:"
          echo $settings | jq

          stages=$(echo $settings | jq -c '.promotion_order | map("deploy/" + .)')
          echo "Promotion order (stages): ${stages}"

          # store output
          echo "stages=${stages}" >> $GITHUB_OUTPUT
      - name: Calculate Target Refs
        id: calc-target-refs
        run: |
          # get settings
          settings="${{ needs.discover.outputs.map }}"

          # extract promotion stages
          stages=$(echo $settings | jq -c '.promotion_order | map("deploy/" + .)')

          # filter out the first stage and extract the target refs without the :auto flags
          targetRefs=$(echo $stages | jq -cr '. | map(split(":")[0]) | .[1:]')
          echo "targetRefs=${targetRefs}" >> $GITHUB_OUTPUT
      - name: Find Promotion Request
        id: find
        uses: sorinlg-beta/promotion-actions/find-promotion-request@main
        with:
          targetRefs: '${{ steps.calc-target-refs.outputs.targetRefs }}'
      - name: Fast-Forward Merge
        id: merge
        if: ${{ steps.find.outputs.promoteable == 'true' }}
        uses: sorinlg-beta/promotion-actions/fast-forward-merge@main
        with:
          baseRef: ${{ steps.find.outputs.baseRef }}
          headRef: ${{ steps.find.outputs.headRef }}
      - name: Request Promotion
        id: promote
        if: ${{ steps.find.outputs.promoteable == 'true' }}
        uses: sorinlg-beta/promotion-actions/open-promotion-request@main
        with:
          stages: ${{ steps.get_promotion_settings.outputs.stages }}
          source: ${{ steps.find.outputs.baseRef }}
